Version: '3.1'

services:
  mariadb:
    image: linuxserver/mariadb:arm32v6-latest
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    ports:
      - 5432:5432
    volumes:
      - /mnt/data/nextcloud/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=P@ssw0rd123
      - MYSQL_ROOT_PASSWORD=P@ssw0rd123
      - MYSQL_DATABASE=nextcloud
    restart: unless-stopped
    hostname: nextcloud-mariadb

  nextcloud-app:
    image: nextcloud:latest
    ports:
      - 80:80
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - mariadb
    volumes:
      - /mnt/data/nextcloud/app/html:/var/www/html
      - /mnt/data/nextcloud/app/config:/var/www/html/config
      - /mnt/data/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /mnt/data/nextcloud/app/data:/var/www/html/data:rw
      - /mnt/data/nextcloud/app/themes:/var/www/html/themes
      - /mnt/data/nextcloud:/data/nextcloud:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERWRITEHOST=192.168.1.10
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_DATA_DIR=/data/nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=P@ssw0rd123
      - MYSQL_DATABASE=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=P@ssw0rd123
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.10
      - MYSQL_HOST=nextcloud-mariadb
    restart: unless-stopped

networks:
  nextcloud_network:
