version: '3.1'

services:

  postgres:
    image: postgres:latest
    container_name: nextcloud-postgres
    networks:
      - nextcloud_network
    volumes:
      - /data/nextcloud/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=P@ssw0rd123
      - POSTGRES_DB=nextcloud
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud:latest
    ports:
      - 80:80
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    depends_on:
      - postgres
    volumes:
      - /data/nextcloud/app/html:/var/www/html
      - /data/nextcloud/app/config:/var/www/html/config
      - /data/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /data/nextcloud/app/data:/var/www/html/data:rw
      - /data/nextcloud/app/themes:/var/www/html/themes
      - /media/pi/data:/data/nextcloud:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OVERWRITEHOST=192.168.1.1
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_DATA_DIR=/data/nextcloud
      - POSTGRES_USER=nextcloud      
      - POSTGRES_PASSWORD=P@ssw0rd123
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=P@ssw0rd123
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.1
    restart: unless-stopped

networks:
  nextcloud_network:
